// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Id       int64  `json:"id"`
	Name     string `path:"name,options=you|me"`
	NickName string `json:"nickName"`
	Age      uint   `json:"age"`
}

type Response struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	NickName string `json:"nickName"`
	Age      uint   `json:"age"`
}
