// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "github.com/GitSorcerer/go-zero-stu/user-api-grpc/internal/handler/user"
	"github.com/GitSorcerer/go-zero-stu/user-api-grpc/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TestMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/info",
					Handler: user.UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/:id",
					Handler: user.UserDescHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/body",
					Handler: user.UserBodyHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
