// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoBody struct {
	UserId int64 `json:"userId"`
	Id     int64 `json:"id"`
}

type UserInfoReq struct {
	UserId int64 `json:"userId"`
	Id     int64 `path:"id"`
}

type UserInfoResp struct {
	UserId       int64 `json:"userId"`
	RefreshAfter int64 `json:"refreshAfter"`
}
